spring.application.name=pharma-auth-service
server.port=9092
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=admin
spring.datasource.password=2006
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=VerySecretKeyForJWTAuthenticationVerySecretKey
jwt.expiration=86400000
notification.service.url=http://localhost:9096